Web/Models/Menu/AddMenuViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.Models.Menu
{
    public class AddMenuViewModel
    {
        public int ProviderId { get; set; }
        [Required(ErrorMessage = "InfoNotSpecified")]
        [Display(Name = "Info")]
        public string Info { get; set; }
        [Required(ErrorMessage = "DateNotSpecified")]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
    }
}

Web/Models/Menu/EditMenuViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.Models.Menu
{
    public class EditMenuViewModel
    {
        public int ProviderId { get; set; }
        public int Id { get; set; }
        [Required(ErrorMessage = "InfoNotSpecified")]
        [Display(Name = "Info")]
        public string Info { get; set; }
        [Required(ErrorMessage = "DateNotSpecified")]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
    }
}

Web/Models/Menu/MenuAndProviderIdViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Web.Models.Menu
{
    public class MenuAndProviderIdViewModel
    {
        public int ProviderId { get; set; }
        public List<MenuViewModel> Menus { get; set; }
        public SelectList SearchSelection { get; set; }
        public string SeacrhString { get; set; }
        public string SearchSelectionString { get; set; }
    }
}

Web/Models/Menu/MenuViewModel.cs
using System;

namespace Web.Models.Menu
{
    public class MenuViewModel
    {
        public int Id { get; set; }
        public string Info { get; set; }
        public DateTime Date { get; set; }
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }

    }
}

Web/Models/Menu/SortState.cs
namespace Web.Models.Menu
{
    public enum SortState
    {
        DateAsc, // по дате по возрастанию
        DateDesc    // по дате по убыванию
    }
}

Web/Controllers/MenuController.cs
using ApplicationCore.DTO;
using ApplicationCore.Exceptions;
using ApplicationCore.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Web.Models.Menu;

namespace Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly IProviderService _providerService;
        private readonly ILogger<MenuController> _logger;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public MenuController(IMenuService menuService, IProviderService providerService,
            ILogger<MenuController> logger,
            IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _menuService = menuService;
            _logger = logger;
            _providerService = providerService;
            _sharedLocalizer = sharedLocalizer;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index(int? providerId, string searchSelectionString, string name, SortState sortMenu = SortState.DateAsc)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Index");

            try
            {
                IEnumerable<MenuDTO> menusDtos = _menuService.GetMenus(providerId);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MenuDTO, MenuViewModel>()).CreateMapper();
                var menus = mapper.Map<IEnumerable<MenuDTO>, List<MenuViewModel>>(menusDtos);

                var provider = _providerService.GetProvider(providerId);

                if (provider == null)
                    throw new ValidationException(_sharedLocalizer["ProviderNoFind"], "");

                ViewData["NameProvider"] = "" + provider.Name;

                // элементы поиска
                List<string> searchSelection = new List<string>() { _sharedLocalizer["SearchBy"], _sharedLocalizer["SearchInfo"], _sharedLocalizer["SearchDateAdd"] };

                if (name == null)
                    name = "";

                // простой поиск

                if (searchSelectionString== searchSelection[1])
                    menus = menus.Where(e => e.Info.ToLower().Contains(name.ToLower())).ToList();
                else if (searchSelectionString == searchSelection[2])
                    menus = menus.Where(t => t.Date.ToShortDateString().Contains(name.ToLower())).ToList();

                ViewData["DateSort"] = sortMenu == SortState.DateAsc ? SortState.DateDesc : SortState.DateAsc;

                menus = sortMenu switch
                {
                    SortState.DateDesc => menus.OrderByDescending(s => s.Date).ToList(),
                    _ => menus.OrderBy(s => s.Date).ToList(),
                };

                return View(new MenuAndProviderIdViewModel()
                {
                    Menus = menus,
                    ProviderId = providerId.Value,
                    SeacrhString = name,
                    SearchSelection = new SelectList(searchSelection),
                    SearchSelectionString = searchSelectionString
                });
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
            }

            return BadRequest(_sharedLocalizer["BadRequest"]);
        }

        #region For admin
      
        [HttpGet]
        public IActionResult Add(int providerId)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Add");

            return View(new AddMenuViewModel() { ProviderId = providerId });
        }

        [HttpPost]
        public IActionResult Add(AddMenuViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MenuDTO menuDTO = new MenuDTO()
                    {
                        Info = model.Info,
                        ProviderId = model.ProviderId,
                        Date = model.Date
                    };

                    _menuService.AddMenu(menuDTO);

                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} added new menu");

                    return RedirectToAction("Index", new { model.ProviderId });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int? id, int providerId, string searchSelectionString, string name)
        {
            try
            {
                _menuService.DeleteMenu(id);

                string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} deleted menu {id}");

                return RedirectToAction("Index", new { providerId, searchSelectionString, name });
            }
            catch (ValidationException ex)
            {
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                return Content(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Edit");

            try
            {
                MenuDTO menuDTO = _menuService.GetMenu(id);
                if (menuDTO == null)
                    throw new ValidationException(_sharedLocalizer["MenuNoFind"], "");

                var provider = new EditMenuViewModel()
                {
                    Id = menuDTO.Id,
                    Date = menuDTO.Date,
                    Info = menuDTO.Info,
                    ProviderId = menuDTO.ProviderId
                };

                return View(provider);
            }
            catch (ValidationException ex)
            {
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Edit(EditMenuViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MenuDTO menuDto = new MenuDTO
                    {
                        Id = model.Id,
                        Date = model.Date,
                        Info = model.Info,
                        ProviderId = model.ProviderId
                    };

                    _menuService.EditMenu(menuDto);

                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} edited menu {model.Id}");

                    return RedirectToAction("Index", new { providerId = model.ProviderId });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                }
            }
            return View(model);
        }

        #endregion
    }
}

Web/Controllers/MenuDishesController.cs
using ApplicationCore.Constants;
using ApplicationCore.DTO;
using ApplicationCore.Exceptions;
using ApplicationCore.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using Web.Models.MenuDishes;

namespace Web.Controllers
{
    public class MenuDishesController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly IProviderService _providerService;
        private readonly ILogger<MenuController> _logger;
        private readonly ICatalogService _catalogService;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        private readonly string _path;

        public MenuDishesController(IMenuService menuService, IProviderService providerService,
            ICatalogService catalogService,
            IStringLocalizer<SharedResource> sharedLocalizer,
            ILogger<MenuController> logger)
        {
            _menuService = menuService;
            _providerService = providerService;
            _logger = logger;
            _path = PathConstants.pathDish;
            _catalogService = catalogService;
            _sharedLocalizer = sharedLocalizer;
        }

        [HttpGet]
        public IActionResult Index(int? menuId, string searchSelectionString, string name,
            string filterCatalog,
            SortStateMenuDishes sortMenuDish = SortStateMenuDishes.PriceAsc)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request MenuDishes/Index");

            try
            {
                var menu = _menuService.GetMenu(menuId);

                if (menu == null)
                    throw new ValidationException($"{_sharedLocalizer["Menu"]} {menuId} {_sharedLocalizer["ItNoFind"]}", "");

                var provider = _providerService.GetProvider(menu.ProviderId);

                if (provider == null)
                    throw new ValidationException($"{_sharedLocalizer["Provider"]} {menu.ProviderId} {_sharedLocalizer["NoFind"]}", "");

                ViewData["NameMeniDishes"] = $"{_sharedLocalizer["Dishes"]} {provider.Name} {_sharedLocalizer["On"]} " + menu.Date.ToShortDateString();

                IEnumerable<MenuDishesDTO> menuDishesDTOs = _menuService.GetMenuDishes(menuId);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MenuDishesDTO, MenuDishesViewModel>()).CreateMapper();
                var menuDishes = mapper.Map<IEnumerable<MenuDishesDTO>, List<MenuDishesViewModel>>(menuDishesDTOs);

                List<int> catalogFilterId = new List<int>() { -1};
                List<string> catalogFilterName = new List<string>() { _sharedLocalizer["FilterAll"] };
               
                // элементы поиска
                List<string> searchSelection = new List<string>() { _sharedLocalizer["SearchBy"], _sharedLocalizer["SearchName"], _sharedLocalizer["SearchInfo"], _sharedLocalizer["SearchWeight"], _sharedLocalizer["SearchPrice"] };

                foreach (var mD in menuDishes)
                {
                    mD.Path = _path + mD.Path;

                    if (!catalogFilterId.Contains(mD.CatalogId))
                    {
                        catalogFilterId.Add(mD.CatalogId);
                        catalogFilterName.Add(_catalogService.GetСatalog(mD.CatalogId).Name);
                    }
                }

                // filter catalog
                if (filterCatalog != null && filterCatalog != catalogFilterName[0])
                {
                    int idCatalogFilterName = catalogFilterName.IndexOf(filterCatalog);
                    menuDishes = menuDishes.Where(p => p.CatalogId == catalogFilterId[idCatalogFilterName]).ToList();
                }
             
                if (name == null)
                    name = "";
                
                // простой поиск
                if (searchSelectionString== searchSelection[1])
                    menuDishes = menuDishes.Where(n => n.Name.ToLower().Contains(name.ToLower())).ToList();
                else if (searchSelectionString == searchSelection[2])
                    menuDishes = menuDishes.Where(e => e.Info.ToLower().Contains(name.ToLower())).ToList();
                else if (searchSelectionString == searchSelection[3])
                    menuDishes = menuDishes.Where(t => t.Weight.ToString() == name).ToList();
                else if (searchSelectionString == searchSelection[4])
                    menuDishes = menuDishes.Where(t => t.Price.ToString() == name).ToList();

                ViewData["PriceSort"] = sortMenuDish == SortStateMenuDishes.PriceAsc ? SortStateMenuDishes.PriceDesc : SortStateMenuDishes.PriceAsc;

                menuDishes = sortMenuDish switch
                {
                    SortStateMenuDishes.PriceDesc => menuDishes.OrderByDescending(s => s.Price).ToList(),
                    _ => menuDishes.OrderBy(s => s.Price).ToList(),
                };

                return View(new ListMenuDishViewModel()
                {
                    MenuId = menuId.Value,
                    MenuDishes = menuDishes,
                    SeacrhString = name,
                    SearchSelection = new SelectList(searchSelection),
                     FilterCategorySelection = new SelectList(catalogFilterName),
                    SearchSelectionString = searchSelectionString,
                     ProviderId = menu.ProviderId,
                      FilterCatalog = filterCatalog
                });
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
            }

            return BadRequest(_sharedLocalizer["BadRequest"]);
        }
    }
}

Web/Views/Menu/Add.cshtml
@model Web.Models.Menu.AddMenuViewModel
@{
    ViewBag.Title = "Добавление меню";
}
<h1 class="text-center">Добавление меню</h1>
<br/>
<form method="post" asp-controller=Menu asp-action="Add">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="ProviderId" />
    <div class="form-group">
        <label asp-for="Info" class="control-label">Информация</label>
        <input type="text" asp-for="Info" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Date" class="control-label">Дата</label>
        <input type="date" asp-for="Date" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-outline-secondary" />
    </div>
</form>

Web/Views/Menu/Edit.cshtml
@model Web.Models.Menu.EditMenuViewModel

@{
    ViewData["Title"] = "Изменение меню";
}

<h1 class="text-center">Изменение меню на @Model.Date.Date</h1>
<br/>

<form method="post" asp-controller="Menu" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ProviderId" />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Info" class="control-label">Информация</label>
        <input type="text" asp-for="Info" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Date" class="control-label">Дата</label>
        <input type="date" asp-for="Date" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Изменить" class="btn btn-outline-secondary" />
    </div>
</form>

Web/Views/Menu/Index.cshtml
@model Web.Models.Menu.MenuAndProviderIdViewModel

@{
    ViewData["Title"] = "Меню";
}

@if (User.IsInRole("admin"))
{
    <a class="btn btn-sm btn-success"  asp-controller="Menu" asp-action="Add" asp-route-providerId="@Model.ProviderId">Добавить меню</a>
}

<h1 class="text-center">Меню  "@ViewData["NameProvider"]"</h1>
<br/>

<form method="get">
    <input type="hidden" name="providerId" value="@Model.ProviderId" />
    <div class="form-inline form-group">
        <label  style="margin-left: 5px;" class="control-label">Поиск по: </label>
        <select  style="margin-left: 5px;" name="searchSelectionString" asp-items="Model.SearchSelection" asp-for="SearchSelectionString" class="form-control"></select>
        <label  style="margin-left: 5px;" class="control-label">Значение: </label>
        <input  style="margin-left: 5px;" name="name" class="form-control" asp-for="SeacrhString" />
        <input class="btn btn-sm btn-success"  style="margin-left: 5px;" type="submit" value="Поиск" />
        <a  style="margin-left: 5px;" class="btn btn-sm btn-success" asp-action="Index" asp-route-providerId="@Model.ProviderId">Обновить</a>
    </div>
</form>
@if (Model.Menus.Any())
{

    <table class="table">
        <tr>
            <th>
                <a asp-action="Index" asp-route-providerId="@Model.ProviderId" asp-route-sortMenu="@ViewBag.DateSort"
                   asp-route-searchSelectionString="@Model.SearchSelectionString" asp-route-name="@Model.SeacrhString">
                    Меню на
                </a>
            </th>
            <th>Информация</th>

            <th></th>
            <th></th>
        </tr>

        @foreach (var menu in Model.Menus)
        {
    <tr>
        <td>@menu.Date.ToShortDateString()</td>
        <td>@menu.Info</td>
        <td><a class="btn btn-sm btn-primary" asp-controller="MenuDishes" asp-action="Index" asp-route-menuId="@menu.Id">Блюда</a></td>
        @if (User.IsInRole("admin"))
        {
            <td>
                <form asp-action="Delete" asp-route-id="@menu.Id"
                      asp-route-providerId="@menu.ProviderId"
                      asp-route-searchSelectionString="@Model.SearchSelectionString"
                      asp-route-name="@Model.SeacrhString"
                      method="post">
                    <input type="hidden" name="providerId" value="@Model.ProviderId" />
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@menu.Id">Изменить</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Удалить
                    </button>
                </form>
            </td>

        }
    </tr>
        }
    </table>
}
else
{
    <h3 class="text-center" style="color:red;">Меню отсутствует</h3>
}