Web/Controllers/CartController.cs
using ApplicationCore.Constants;
using ApplicationCore.DTO;
using ApplicationCore.Exceptions;
using ApplicationCore.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using Web.Models.Cart;

namespace Web.Controllers
{
    [Authorize]
    public class CartController:Controller
    {
        private readonly ICartService _cartService;
        private readonly ILogger<CartController> _logger;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        private readonly string _path;

        public CartController(ICartService cartService,
             IStringLocalizer<SharedResource> sharedLocalizer,
             ILogger<CartController> logger)
        {
            _cartService = cartService;
            _logger = logger;
            _path = PathConstants.pathDish;
            _sharedLocalizer = sharedLocalizer;
        }

        [Authorize(Roles = "employee")]
        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Cart/Index");

            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    CartDTO cartDTO = _cartService.GetCart(currentUserId);

                    IEnumerable<CartDishesDTO> cartDishDTO = _cartService.GetCartDishes(currentUserId);
                    var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CartDishesDTO, CartDishesViewModel>()).CreateMapper();
                    var cartDishes = mapper.Map<IEnumerable<CartDishesDTO>, List<CartDishesViewModel>>(cartDishDTO);

                    foreach (var cD in cartDishes)
                    {
                        cD.Path = _path + cD.Path;
                    }

                 ViewData["FullPrice"] =  _cartService.FullPriceCart(currentUserId);

                    return View(cartDishes);
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property} {ex.Message}");
                }

                return BadRequest(_sharedLocalizer["BadRequest"]);
            }

            return RedirectToAction("Login","Account");
        }

        [Authorize(Roles = "employee")]
        [HttpPost]
        public IActionResult Delete(int? cartDishId)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _cartService.DeleteCartDish(cartDishId, currentUserId);

                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} deleted cartDish {cartDishId}");

                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property} {ex.Message}");
                }

                return BadRequest(_sharedLocalizer["BadRequest"]);
            }

            return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "employee")]
        [HttpGet]
        public IActionResult Add(int? dishId)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Cart/Add");

            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _cartService.AddDishToCart(dishId, currentUserId);

                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} add dish {dishId}");

                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property} {ex.Message}");
                }

                return BadRequest(_sharedLocalizer["BadRequest"]);
            }

            return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "employee")]
        [HttpPost]
        public IActionResult DeleteAll()
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _cartService.AllDeleteDishesToCart(currentUserId);

                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} emptied the cart");

                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property} {ex.Message}");
                }

                return BadRequest(_sharedLocalizer["BadRequest"]);
            }
            return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "employee")]
        [HttpPost]
        public IActionResult Update(int? dishCartId, int count)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                _cartService.UpdateCountDishInCart(currentUserId, dishCartId, count);

                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} updated count dishCart {dishCartId}");

                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property} {ex.Message}");
                }

                return BadRequest(_sharedLocalizer["BadRequest"]);
            }

            return RedirectToAction("Login", "Account");
        }       
    }
}

Web/Controllers/MenuController.cs
using ApplicationCore.DTO;
using ApplicationCore.Exceptions;
using ApplicationCore.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Web.Models.Menu;

namespace Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly IProviderService _providerService;
        private readonly ILogger<MenuController> _logger;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public MenuController(IMenuService menuService, IProviderService providerService,
            ILogger<MenuController> logger,
            IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _menuService = menuService;
            _logger = logger;
            _providerService = providerService;
            _sharedLocalizer = sharedLocalizer;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index(int? providerId, string searchSelectionString, string name, SortState sortMenu = SortState.DateAsc)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Index");

            try
            {
                IEnumerable<MenuDTO> menusDtos = _menuService.GetMenus(providerId);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MenuDTO, MenuViewModel>()).CreateMapper();
                var menus = mapper.Map<IEnumerable<MenuDTO>, List<MenuViewModel>>(menusDtos);

                var provider = _providerService.GetProvider(providerId);

                if (provider == null)
                    throw new ValidationException(_sharedLocalizer["ProviderNoFind"], "");

                ViewData["NameProvider"] = "" + provider.Name;

                // элементы поиска
                List<string> searchSelection = new List<string>() { _sharedLocalizer["SearchBy"], _sharedLocalizer["SearchInfo"], _sharedLocalizer["SearchDateAdd"] };

                if (name == null)
                    name = "";

                // простой поиск

                if (searchSelectionString== searchSelection[1])
                    menus = menus.Where(e => e.Info.ToLower().Contains(name.ToLower())).ToList();
                else if (searchSelectionString == searchSelection[2])
                    menus = menus.Where(t => t.Date.ToShortDateString().Contains(name.ToLower())).ToList();

                ViewData["DateSort"] = sortMenu == SortState.DateAsc ? SortState.DateDesc : SortState.DateAsc;

                menus = sortMenu switch
                {
                    SortState.DateDesc => menus.OrderByDescending(s => s.Date).ToList(),
                    _ => menus.OrderBy(s => s.Date).ToList(),
                };

                return View(new MenuAndProviderIdViewModel()
                {
                    Menus = menus,
                    ProviderId = providerId.Value,
                    SeacrhString = name,
                    SearchSelection = new SelectList(searchSelection),
                    SearchSelectionString = searchSelectionString
                });
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
            }

            return BadRequest(_sharedLocalizer["BadRequest"]);
        }

        #region For admin
      
        [HttpGet]
        public IActionResult Add(int providerId)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Add");

            return View(new AddMenuViewModel() { ProviderId = providerId });
        }

        [HttpPost]
        public IActionResult Add(AddMenuViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MenuDTO menuDTO = new MenuDTO()
                    {
                        Info = model.Info,
                        ProviderId = model.ProviderId,
                        Date = model.Date
                    };

                    _menuService.AddMenu(menuDTO);

                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} added new menu");

                    return RedirectToAction("Index", new { model.ProviderId });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int? id, int providerId, string searchSelectionString, string name)
        {
            try
            {
                _menuService.DeleteMenu(id);

                string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} deleted menu {id}");

                return RedirectToAction("Index", new { providerId, searchSelectionString, name });
            }
            catch (ValidationException ex)
            {
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                return Content(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            _logger.LogInformation($"{DateTime.Now.ToString()}: Processing request Menu/Edit");

            try
            {
                MenuDTO menuDTO = _menuService.GetMenu(id);
                if (menuDTO == null)
                    throw new ValidationException(_sharedLocalizer["MenuNoFind"], "");

                var provider = new EditMenuViewModel()
                {
                    Id = menuDTO.Id,
                    Date = menuDTO.Date,
                    Info = menuDTO.Info,
                    ProviderId = menuDTO.ProviderId
                };

                return View(provider);
            }
            catch (ValidationException ex)
            {
                _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Edit(EditMenuViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MenuDTO menuDto = new MenuDTO
                    {
                        Id = model.Id,
                        Date = model.Date,
                        Info = model.Info,
                        ProviderId = model.ProviderId
                    };

                    _menuService.EditMenu(menuDto);

                    string currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _logger.LogInformation($"{DateTime.Now.ToString()}: User {currentUserId} edited menu {model.Id}");

                    return RedirectToAction("Index", new { providerId = model.ProviderId });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                    _logger.LogError($"{DateTime.Now.ToString()}: {ex.Property}, {ex.Message}");
                }
            }
            return View(model);
        }

        #endregion
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @SharedLocalizer["ViewShared_Layout_Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer["MainPage"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Provider">@SharedLocalizer["Providers"]</a>
                        </li>
                        @if (User.IsInRole("employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-action="Index" asp-controller="Cart">@SharedLocalizer["Cart"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-action="Index" asp-controller="Order">@SharedLocalizer["Orders"]</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Users" asp-action="Index">@SharedLocalizer["Users"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Report" asp-action="Index">@SharedLocalizer["Reports"]</a>
                            </li>
                        }
                    </ul>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse justify-content-end">
                        <ul class="navbar-nav text-right">
                            <li class="nav-item">
                                <form class="text-black-50" method="post" asp-controller="Account" asp-action="Logout">
                                    <input class="nav-link text-dark" type="submit" value="@SharedLocalizer["Logout"]" style="outline: none; border: none; background-color: white;" />
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-black-50" asp-area="" asp-controller="Account" asp-action="Profile">@SharedLocalizer["Profil"]</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse justify-content-end">
                        <ul class="navbar-nav text-right">
                            <li class="nav-item">
                                <a class="nav-link text-black-50" asp-area="" asp-controller="Account" asp-action="Login">@SharedLocalizer["Login"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-black-50" asp-area="" asp-controller="Account" asp-action="Register">@SharedLocalizer["Registration"]</a>

                            </li>
                        </ul>
                    </div>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @SharedLocalizer["CopyName"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">@SharedLocalizer["Privacypolicy"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_ProvidersList.cshtml
@model Web.Models.Provider.ProviderViewModel

<div class="col-lg-4">
    @if (Model.Path != null)
    {
        <a asp-action="Index" asp-controller="Menu" asp-route-providerId="@Model.Id"> <img width="360" height="180" class="img-thumbnail" src="@Model.Path" alt="@Model.Name" /></a>
    }
<h2>@SharedLocalizer["Name"]: @Model.Name</h2>
    @if (User.IsInRole("admin"))
    {
<p>@SharedLocalizer["Id"]: @Model.Id </p>
    }
<p>@SharedLocalizer["WorkingDays"]: @Model.WorkingDays </p>
<p>@SharedLocalizer["TimeWork"]: @Model.TimeWorkWith.ToShortTimeString() : @Model.TimeWorkTo.ToShortTimeString()</p>
<p>@SharedLocalizer["Info"]: @Model.Info</p>
<p>@SharedLocalizer["Email"]: @Model.Email</p>
    @if (Model.IsActive)
    {
<p>@SharedLocalizer["StatusActive"]</p>
    }
    else
    {
<p>@SharedLocalizer["StatusInactive"]</p>
    }

    @if (User.IsInRole("admin"))
    {
        <form asp-action="Delete" asp-route-id="@Model.Id" method="post">
            <input type="hidden" name="searchSelectionString" value="@ViewData["SearchSelectionString"]" />
            <input type="hidden" name="name" value="@ViewData["SeacrhString"]" />
            <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@Model.Id">@SharedLocalizer["Edit"]</a>
            <button type="submit" class="btn btn-sm btn-danger">
                @SharedLocalizer["Delete"]
            </button>
        </form>
        <br />
    }
<a class="btn btn-sm btn-primary" asp-action="Index" asp-controller="Menu" asp-route-providerId="@Model.Id">@SharedLocalizer["Menu"]</a>
<a class="btn btn-sm btn-primary" asp-action="Index" asp-controller="Catalog" asp-route-providerId="@Model.Id">@SharedLocalizer["CatalogDishes"]</a>
    <br />
    <br />
</div>